### ISSUE TITLE
Is this for mobile development assignment 4?

### ISSUE THREAD

**Issue by eddieysong** [aagavin/android-datastorage#1]

**Comment by aagavin** [comment]
yep

**Comment by aagavin** [comment]
@eddieysong is there something wrong with it?

**Comment by eddieysong** [comment]
@aagavin no you showed up in the GitHub feed so I dropped by to say hello

H E L L O

**Comment by aagavin** [comment]
# HI

I taught I'd get it started since the strike looks like its going to be over soonish.
